---
sidebar: sidebar 
permalink: codebox-automation.html 
keywords: codebox, automation 
summary: 'CodeBox是一款基础架构即代码(Infrastructure as Code、IAC)联合产品、可帮助开发人员和开发运营团队生成执行工作负载工厂支持的任何操作所需的代码。' 
---
= 了解CODEBox自动化
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
CodeBox是一款基础架构即代码(Infrastructure as Code、IAC)联合产品、可帮助开发人员和开发运营团队生成执行工作负载工厂支持的任何操作所需的代码。Codebox 与工作负载工厂操作模式（_basic_、_read-only_ 和 _read/write_）保持一致，它为执行准备设置了清晰的路径，并提供了自动化目录以供将来快速重用。



== CodeBox功能

CodeBox提供了两项关键IAC功能：

* _CodeBox Viewer_显示了由特定作业流操作生成的IAC，它通过匹配图形向导或对话聊天界面中的条目和选择来生成。尽管CodeBox查看器支持颜色编码以方便导航和分析，但它不允许编辑，仅允许将代码复制或保存到自动化目录中。
* _CodeBox自动化目录_显示所有已保存的IAC作业、便于您轻松参考这些作业以供将来使用。自动化目录作业会另存为模板、并显示在应用于这些作业的资源的上下文中。


此外、在设置工作负载出厂凭据时、Codebox会动态显示创建IAM策略所需的AWS权限。这些权限是为您计划使用的每个工作负载工厂功能（数据库、AI、FSx for ONTAP 等）提供的，并且根据策略用户是否获得_只读_权限或完全_读/写_权限进行定制。您只需从CodeBox复制权限、然后将其粘贴到AWS管理控制台中、以便工作负载工厂拥有正确的权限来管理您的工作负载。



== 支持的代码格式

支持的代码格式包括：

* 工作负载出厂REST API
* AWS命令行界面
* AWS CloudFormation


link:use-codebox.html["了解如何使用CodeBox"](英文)
