---
sidebar: sidebar 
permalink: configure-notifications.html 
keywords: amazon, sns, notification, topic, notifications, notifications service, alerts 
summary: 您可以配置NetApp Workload Factory，在发生某些类型的事件时向某个人或其他应用程序发送通知。 
---
= 配置NetApp Workload Factory 通知
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
您可以配置NetApp Workload Factory 通知服务，以将通知作为NetApp控制台中的警报或 Amazon SNS 主题发送。当您部署控制台代理或链接时，以警报形式发送的通知会出现在NetApp控制台中。当 Workload Factory 向 Amazon SNS 主题发布通知时，该主题的订阅者（例如人员或其他应用程序）会在为该主题配置的端点接收通知（例如电子邮件或短信）。



== 通知类型和消息

Workload Factory 针对以下事件发送通知：

[cols="6*"]
|===
| 事件 | 说明 | 通知类型 | 严重性 | 工作负载 | 资源类型 


| 您帐户中的某些数据库实例架构不佳 | 您的帐户中的所有 Microsoft SQL Server 实例均已针对架构问题进行分析。此事件的描述给出了架构良好的实例和未优化的实例的数量。从工作负载工厂控制台查看数据库清单中精心设计的状态结果和建议。 | 架构完善 | 建议 | 数据库 | Microsoft SQL Server 实例 


| Microsoft SQL Server/PostgreSQL 服务器部署成功 | Microsoft SQL Server 或 PostgreSQL 主机部署成功。更多信息，请参考作业监控。 | 部署 | 成功 | 数据库 | FSx for ONTAP，数据库主机 


| Microsoft SQL Server/PostgreSQL 服务器部署失败 | Microsoft SQL Server 或 PostgreSQL 主机部署失败。更多信息，请参考作业监控。 | 部署 | 错误 | 数据库 | FSx for ONTAP，数据库主机 


| 复制关系创建失败 | SnapMirror复制关系创建失败。欲了解更多信息，请访问 Tracker。 | 复制 | 批判的 | 常规存储 | 适用于ONTAP的 FSx 


| FSx for ONTAP创建失败 | FSx for ONTAP文件系统创建过程失败。欲了解更多信息，请访问 Tracker。 | FSx for ONTAP文件系统操作 | 批判的 | 常规存储 | 适用于ONTAP的 FSx 


| 自动增加 SSD 容量或 inode 成功 | 在最近的自动容量管理更新期间，FSx for ONTAP文件系统成功增加了 SSD 容量或卷 inode。欲了解更多信息，请访问 Tracker。 | 容量管理 | 成功 | 常规存储 | FSx for ONTAP文件 


| 自动增加 SSD 容量或 inode 失败 | 在最近的自动容量管理更新期间，FSx for ONTAP文件系统未能增加 SSD 容量或卷 inode。欲了解更多信息，请访问 Tracker。 | 容量管理 | 批判的 | 常规存储 | FSx for ONTAP文件系统 


| 检测到 FSx for ONTAP问题 | 所有 FSx for ONTAP文件系统均已针对架构问题进行了分析。扫描检测到一个或多个问题。有关更多信息，请查看 Workload Factory 控制台中存储仪表板的精心设计的分析。 | 精心设计的分析 | 建议 | 常规存储 | FSx for ONTAP文件系统 


| FSx for ONTAP的自动容量管理事件 | FSx for ONTAP文件系统的 SSD 性能层级已达到警告阈值容量/百分比总和。 | 容量管理 | 警告 | 常规存储 | FSx for ONTAP文件系统 


| FSx for ONTAP的自动 inode 管理事件 | ONTAP卷的 FSx inode 计数达到警告阈值计数/百分比总数。 | 容量管理 | 警告 | 常规存储 | FSx for ONTAP文件系统 
|===


== 配置工作负载工厂通知

使用NetApp控制台或 Workload Factory 控制台配置 W​​orkload Factory 通知。如果您使用NetApp控制台，则可以配置 Workload Factory 以将通知作为NetApp控制台中的警报或 Amazon SNS 主题发送。您可以从NetApp控制台中的 *通知设置* 配置通知。

.开始之前
* 您需要使用 Amazon SNS 控制台或 AWS CLI 配置 Amazon SNS 并创建 Amazon SNS 主题。
* 请注意，Workload Factory 支持 *标准* 主题类型。这种类型的主题不能确保通知按照收到的顺序发送给订阅者，因此如果您有关键或紧急通知，请考虑这一点。


[role="tabbed-block"]
====
.从NetApp控制台配置通知
--
.步骤
. 登录link:https://console.netapp.com["NetApp控制台"^]。
. 从NetApp控制台菜单中，选择 *Workloads*、*Administration*，然后选择 *Notifications setup*。
. 在通知设置页面上，执行以下操作：
+
.. 可选：选择“启用NetApp控制台通知”以配置 Workload Factory 在NetApp控制台中发送通知。
.. 选择*启用 SNS 通知*。
.. 按照说明从 Amazon SNS 控制台配置 Amazon SNS。
+
创建主题后，复制主题 ARN 并将其输入到 *通知设置* 页面上的 *SNS 主题 ARN* 字段中。



. 通过发送测试通知验证配置后，选择*应用*。


.结果
Workload Factory 已配置为向您指定的 Amazon SNS 主题发送通知。

--
.从 Workload Factory 控制台配置通知
--
.步骤
. 登录link:https://console.workloads.netapp.com["工作负载工厂控制台"^]。
. 从 Workload Factory 控制台菜单中，选择 *Workloads*、*Administration*，然后选择 *Notifications setup*。
. 选择*启用 SNS 通知*。
. 按照说明从 Amazon SNS 控制台配置 Amazon SNS。
. 通过发送测试通知验证配置后，选择*应用*。


.结果
Workload Factory 已配置为向您指定的 Amazon SNS 主题发送通知。

--
====


== 订阅 Amazon SNS 主题

配置 Workload Factory 向主题发送通知后，请按照 https://docs.aws.amazon.com/sns/latest/dg/sns-create-subscribe-endpoint-to-topic.html["说明"]在 Amazon SNS 文档中订阅该主题，以便您可以接收来自 Workload Factory 的通知。



== 筛选通知

您可以通过对通知应用过滤器来减少不必要的通知流量，并为特定用户提供特定的通知类型。您可以使用 Amazon SNS 策略来发送 SNS 通知，并使用NetApp控制台中的通知设置来执行此操作。



=== 筛选 Amazon SNS 通知

当您订阅 Amazon SNS 主题时，默认情况下您会收到发布到该主题的所有通知。如果您只想接收来自主题的特定通知，则可以使用过滤策略来控制接收哪些通知。过滤策略使 Amazon SNS 仅向订阅者发送符合过滤策略的通知。

您可以按照以下条件筛选 Amazon SNS 通知：

[cols="3*"]
|===
| 说明 | 过滤策略字段名称 | 可能值 


| 资源类型 | `resourceType`  a| 
* `DB`
* `Microsoft SQL Server host`
* `PostgreSQL Server host`




| 工作负载 | `workload` | `WLMDB` 


| 优先级 | `priority`  a| 
* `Success`
* `Info`
* `Recommendation`
* `Warning`
* `Error`
* `Critical`




| 通知类型 | `notificationType`  a| 
* `Deployment`
* `Well-architected`


|===
.步骤
. 在 Amazon SNS 控制台中，编辑 SNS 主题的订阅详细信息。
. 在*订阅过滤策略*区域，选择按*消息属性*进行过滤。
. 启用*订阅过滤策略*选项。
. 在 *JSON 编辑器* 框中输入 JSON 过滤策略。
+
例如，以下 JSON 过滤策略接受来自 Microsoft SQL Server 资源的与 WLMDB 工作负载相关的通知，优先级为成功或错误，并提供有关 Well-architected 状态的详细信息：

+
[source, json]
----
{
  "accountId": [
    "account-a"
  ],
  "resourceType": [
    "Microsoft SQL Server host"
  ],
  "workload": [
    "WLMDB"
  ],
  "priority": [
    "Success",
    "Error"
  ],
  "notificationType": [
    "Well-architected"
  ]
}
----
. 选择“保存更改”。


有关过滤策略的其他示例，请参阅 https://docs.aws.amazon.com/sns/latest/dg/example-filter-policies.html["Amazon SNS 示例筛选策略"^]。

有关创建过滤策略的更多信息，请参阅 https://docs.aws.amazon.com/sns/latest/dg/sns-message-filtering.html["Amazon SNS文档"^]。



=== NetApp控制台中的过滤通知

您可以使用NetApp控制台通知设置按严重性级别（例如“严重”、“信息”或“警告”）过滤控制台中收到的通知。

有关在控制台中过滤通知的更多信息，请参阅 https://docs.netapp.com/us-en/console-setup-admin/task-monitor-cm-operations.html#filter-notifications["NetApp控制台文档"^]。
