---
sidebar: sidebar 
permalink: well-architected-workloads.html 
keywords: well-architected, best practices, well-architected file system, Amazon FSx for NetApp ONTAP, FSx for ONTAP 
summary: Workload Factory 会扫描工作负载配置的可靠性、安全性、卓越运营、成本优化和性能效率，并提供见解和建议，帮助您实现卓越运营。 
---
= 使用 NetApp Workload Factory 构建和操作精心设计的工作负载
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Workload Factory 是用于 Amazon FSx for NetApp ONTAP 的 NetApp 管理套件，可帮助您维护和操作与 AWS Well-Architected Framework 一致的可靠、安全、高效且经济高效的工作负载配置。Workload Factory 提供对您的工作负载的日常分析、建议和自动修复，以促进健康的工作负载操作。通过自动化此流程，Workload Factory 可最大限度地减少人为错误，并确保工作负载管理的一致性。



== 工作原理

Workload Factory 每天分析在 Amazon FSx for NetApp ONTAP 文件系统部署上运行的工作负载。该分析提供了精心设计的状态、见解和建议。

每日分析完成后，部署的配置会在“架构完善”仪表板中显示为“已优化”或“未优化”。您将看到总优化得分、按类别划分的配置问题以及配置问题和建议列表。您可以查看针对配置问题的建议。有些问题可以由工作负载工厂自动修复，而另一些问题则需要人工干预。在这种情况下，工作负载工厂会提供详细的说明来帮助您实施建议的更改。

您可以忽略不适用于您环境的配置分析。这样可以避免不必要的警报和不准确的优化结果。当您忽略特定配置分析时，Workload Factory 不将配置包含在总优化分数中。



== 为什么这很重要

Workload Factory 通过将持续评估与建议见解和补救措施相结合，将最佳实践应用于大型存储、数据库和 VMware 环境。在 Workload Factory 控制台中应用的自动修复可减少人为错误，确保统一管理，并保持整个工作负载基础架构的性能和可靠性。



== 开始使用 Workload Factory 检测和修复工作负载错误配置

要开始使用 Workload Factory，请注册、添加凭据并建立连接，以便使用 Amazon FSx for NetApp ONTAP 管理 AWS 资源并优化工作负载。

link:https://docs.netapp.com/us-en/workload-setup-admin/quick-start.html["快速入门"]



== 相关信息

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["为ONTAP文件系统实现架构良好的 FSx"^]
* link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["实现架构良好的数据库工作负载"^]
* link:https://docs.netapp.com/us-en/workload-vmware/view-evs-well-architected.html["实施精心设计的 EVS 配置"^]

